### ISSUE TITLE
Latest version on Pypi not compatible with setuptools

### ISSUE THREAD

**Issue by rex911** [quatrope/scikit-criteria#18]
`setuptools` recently mandated checking for newlines: https://github.com/pypa/setuptools/commit/a4b7caeaa653116b60a5231e9019ab250293c331

We're observing errors while installing `skcriteria` with setuptools:

``
10:08:12        cwd: /tmp/pip-install-6vgy8g_3/scikit-criteria_a188aa38d71246558652ef0768f8ca3b/
10:08:12   Complete output (29 lines):
10:08:12   Warning: 'classifiers' should be a list, got type 'tuple'
10:08:12   running egg_info
10:08:12   creating /tmp/pip-pip-egg-info-v0lih8ua/scikit_criteria.egg-info
10:08:12   writing /tmp/pip-pip-egg-info-v0lih8ua/scikit_criteria.egg-info/PKG-INFO
10:08:12   Traceback (most recent call last):
10:08:12     File "<string>", line 1, in <module>
10:08:12     File "/tmp/pip-install-6vgy8g_3/scikit-criteria_a188aa38d71246558652ef0768f8ca3b/setup.py", line 115, in <module>
10:08:12       do_setup()
10:08:12     File "/tmp/pip-install-6vgy8g_3/scikit-criteria_a188aa38d71246558652ef0768f8ca3b/setup.py", line 103, in do_setup
10:08:12       install_requires=REQUIREMENTS,
10:08:12     File "/var/lib/jenkins/workspace/pummel_PR-148-5IDUTEJ55KBJ2X3SZN5AW6R3R7KENFHATMRIO6JRRCA2QV3Y7OFA/.nox/linter/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
10:08:12       return distutils.core.setup(**attrs)
10:08:12     File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
10:08:12       dist.run_commands()
10:08:12     File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
10:08:12       self.run_command(cmd)
10:08:12     File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
10:08:12       cmd_obj.run()
10:08:12     File "/var/lib/jenkins/workspace/pummel_PR-148-5IDUTEJ55KBJ2X3SZN5AW6R3R7KENFHATMRIO6JRRCA2QV3Y7OFA/.nox/linter/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 292, in run
10:08:12       writer(self, ep.name, os.path.join(self.egg_info, ep.name))
10:08:12     File "/var/lib/jenkins/workspace/pummel_PR-148-5IDUTEJ55KBJ2X3SZN5AW6R3R7KENFHATMRIO6JRRCA2QV3Y7OFA/.nox/linter/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
10:08:12       metadata.write_pkg_info(cmd.egg_info)
10:08:12     File "/usr/lib/python3.7/distutils/dist.py", line 1117, in write_pkg_info
10:08:12       self.write_pkg_file(pkg_info)
10:08:12     File "/var/lib/jenkins/workspace/pummel_PR-148-5IDUTEJ55KBJ2X3SZN5AW6R3R7KENFHATMRIO6JRRCA2QV3Y7OFA/.nox/linter/lib/python3.7/site-packages/setuptools/dist.py", line 167, in write_pkg_file
10:08:12       write_field('Summary', single_line(self.get_description()))
10:08:12     File "/var/lib/jenkins/workspace/pummel_PR-148-5IDUTEJ55KBJ2X3SZN5AW6R3R7KENFHATMRIO6JRRCA2QV3Y7OFA/.nox/linter/lib/python3.7/site-packages/setuptools/dist.py", line 151, in single_line
10:08:12       raise ValueError('Newlines are not allowed')
10:08:12   ValueError: Newlines are not allowed```

It seems the latest release on Pypi `0.2.11` has this issue 
```
>>> import skcriteria
>>> skcriteria.DOC
'Scikit-Criteria is a collections of algorithms, methods and\ntechniques for multiple-criteria decision analysis.\n\n'
>>> skcriteria.VERSION
'0.2.11'
```

whereas the current `master` does not: https://github.com/quatrope/scikit-criteria/blob/32fb6314f55550fc32ab7899a976fdb75e78e0e6/skcriteria/__init__.py#L12

**Comment by leliel12** [comment]
I just uploaded the version 0.5.dev0, i still need to write a simple "quickstart" and in this week the version 0.5 must be published

**Comment by leliel12** [comment]
Version 0.5 published! please check the new tutorial https://scikit-criteria.readthedocs.io/en/latest/tutorial/quickstart.html

**Comment by rex911** [comment]
Thank you for the new release.

Setuptools also has a new release (https://github.com/pypa/setuptools/issues/2893#issuecomment-981182961) to fix the originally reported issue. I'll close it now.
