### ISSUE TITLE
General doubt

### ISSUE THREAD

**Issue by barbozabarb** [quatrope/scikit-criteria#19]
I am sorry, I'm new with this topic, but does this repository helps for ranking objects like a news feed?

**Comment by leliel12** [comment]
If you can define the criteria to ranks a d create the apropiate decision
matrix, tes you can. Please use the github version of the proyect and chek
the tests for examples i currently ended a big rewrite

**Comment by barbozabarb** [comment]
@leliel12 Gracias Juan! Que orgullo que me responda un conicetero. Yo estudio en exactas de la uba.
Sabes estoy haciendo un miniproyecto en donde ahora tengo que implementar un algoritmo de rankeo muy simple, pero hace dias que estoy buscando y no logro encontrar información?

Seria un feed de imagenes tageadas donde se organizan las imagenes entre las mas populares (votos positivos, comentarios, comparidos), pero mezclada con las imagenes nuevas que suben algunos usuarios (Osea si algo recien se publico tiene igual de relevancia que algo popular, y se ve si es bien recibido o no) 
Algo parecido al instagram.

Tenes algunos recursos o links sobre para donde deberia leer mas sobre este tipo de algoritmo?

**Comment by leliel12** [comment]
Si me podes mandar un mail, asi te paso material. Y cerra este ticket please,  a jbcabral@unc.edu.ar

**Comment by barbozabarb** [comment]
Gracias
