### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by hadim** [quatrope/scikit-criteria#20]
For info I have made a conda package of scikit-criteria at https://github.com/conda-forge/scikit-criteria-feedstock

```bash
mamba install -c conda-forge scikit-criteria
```

ping @leliel12 

(you can close once you've read this)

**Comment by hadim** [comment]
Also could you bump a new version. It looks like the API has changed between the pypi package and the `master` branch.

**Comment by leliel12** [comment]
yes I can, but please wait until next week. In the south we are closing the year with all the academic problems that generate. What I am missing are tutorials. I radically changed the API and although it works much better now, the tutorials are no longer useful.

Currently (and for the past 5 years) I am almost the only developer

**Comment by hadim** [comment]
I totally understand. Take as much time as you need, this is a more friendly reminder that a hard request obviously!

And thanks for your nice library.

**Comment by leliel12** [comment]
You’re welcome and thank you for taking the time to maintain the conda package. Much appreciated”

**Comment by leliel12** [comment]
I just uploaded the version 0.5.dev0, i still need to write a simple "quickstart" and in this week the version 0.5 must be published

**Comment by leliel12** [comment]
Version 0.5 published

**Comment by hadim** [comment]
That's great. 0.5 is also available in conda-forge now: https://github.com/conda-forge/scikit-criteria-feedstock

Thanks again for the help here!

**Comment by leliel12** [comment]
I gonna add the tutorial to install from condaforge
