### ISSUE TITLE
Is `skcriteria.madm.simple.WeightedSum()` depreciated?

### ISSUE THREAD

**Issue by Saugatkafley** [quatrope/scikit-criteria#39]
How to get the rank column like in the example , 
![image](https://user-images.githubusercontent.com/52364337/181793031-6c8dbe5f-bb17-4e7e-b4a2-3171a82c35d5.png)

I think the module is depreciated . 
It would be helpful if the last working version could be found.

**Comment by leliel12** [comment]
The entire API os scikit-criteria was changed on version 0.5. Please check the current tutorial of the project here

https://scikit-criteria.quatrope.org/en/latest/tutorial/quickstart.html

Please join the group https://groups.google.com/g/scikit-criteria for future questions. The issues are for report bugs and assign task

please close the issue after read
