### ISSUE TITLE
Fix min-max for minimize

### ISSUE THREAD

**Issue by leliel12** [quatrope/scikit-criteria#43]

**Comment by cwognum** [comment]
Hi @leliel12! I just came across this repo. Thank you for this great work! 

Could you elaborate on this issue? I was wondering what it's implications are w.r.t. using some of these methods. If it's something I can help, I would be happy to contribute towards a solution.

**Comment by leliel12** [comment]
First: thank you for your interest in the project and I can look for another good first issue.
Second: This issue is invalid

Now the story:

I was taking a course on advanced multicriteria and I saw that some authors use two formulas for min-max depending on whether the criterion is minimization or maximization.

- Maximization

    $$
         x_{scaled} = \frac{x - x_{min}}{x_{max} - x_{min}}
    $$


- Minimization

$$
     x_{scaled} = \frac{x - x_{max}}{x_{min} - x_{max}}
$$

The problem with this strategy is that if the criterion is a **minimization** criterion, what these formulas do is not only normalize but also turn it into a **maximization** criterion.

**That is:** using the two formulas does **two** things at the same time.

This is not desirable in the long run and I prefer to keep the concepts of scaling and inversion of criteria separate to reduce potential bugs.

**Comment by cwognum** [comment]
Clear! Thanks for taking the time to explain!
