### ISSUE TITLE
errors in the documentation

### ISSUE THREAD

**Issue by SalvatoreRa** [quatrope/scikit-criteria#47]
Hello,

very nice works, I am testing the methods. I have just noted that there is an error in the documentation:

https://scikit-criteria.quatrope.org/en/latest/tutorial/quickstart.html

```
In the tutorial:
from skcriteria.agg import simple
what actually work:
from skcriteria.madm import simple
```

**Comment by leliel12** [comment]
You are using an old version of scikit criteria, sadly I have a bug on the
windows package and no time to fix it

**Comment by SalvatoreRa** [comment]
I have installed it today using:

```
#installation command
pip install git+https://github.com/quatrope/scikit-criteria/
```

**Comment by leliel12** [comment]
Agg must work, if you are using master
